# Numpy Part-2

In [2]:
import numpy as np

### 4. Operation

In [3]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum 및 axis

In [4]:
# 모든 요소들의 합
a.sum()

78

In [5]:
# 열의 합
a.sum(axis=0)

array([15, 18, 21, 24])

In [6]:
# 행의 합
a.sum(axis=1)

array([10, 26, 42])

In [8]:
np.sum(a[1])

26

In [10]:
a.min(axis=0)

array([1, 2, 3, 4])

In [11]:
a.max(axis=1)

array([ 4,  8, 12])

In [12]:
a.mean()

6.5

In [13]:
a.mean(axis=0), a.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

- sorting

In [14]:
b = np.array([[4,3,5,7],[1,12,11,9],[2,5,1,14]])
b

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2,  5,  1, 14]])

In [15]:
np.sort(b)      # axis = 1, ascending order

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [16]:
np.sort(b, axis=0)

array([[ 1,  3,  1,  7],
       [ 2,  5,  5,  9],
       [ 4, 12, 11, 14]])

In [19]:
b.sort()
b

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2,  5, 14]])

In [20]:
b.sort(axis=0)
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [22]:
# 내림차순
c = np.array([42, 38, 12, 25])
np.sort(c)[::-1]

array([42, 38, 25, 12])

In [23]:
np.argsort(c)

array([2, 3, 1, 0], dtype=int64)

In [24]:
c[[2,3,1,0]]

array([12, 25, 38, 42])

In [25]:
indices = np.argsort(c)
c[indices]

array([12, 25, 38, 42])

- Mathematical functions

In [26]:
# sigmoid 함수
def sigmoid(x):
    return 1. / (1 + np.exp(-x))

In [27]:
X = np.array([-10,0,10])
sigmoid(X)

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose(전치)

In [28]:
b

array([[ 1,  2,  5,  7],
       [ 1,  4,  5, 12],
       [ 3,  9, 11, 14]])

In [29]:
b.T

array([[ 1,  1,  3],
       [ 2,  4,  9],
       [ 5,  5, 11],
       [ 7, 12, 14]])

- concatenate, vstack, hstack

In [31]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [32]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [34]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [38]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 5. Array operation

- 4칙 연산

In [39]:
a

array([[1, 2],
       [3, 4]])

In [40]:
a + a

array([[2, 4],
       [6, 8]])

In [41]:
a - a

array([[0, 0],
       [0, 0]])

In [42]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [43]:
a / a

array([[1., 1.],
       [1., 1.]])

- Broadcasting

In [44]:
a + 3

array([[4, 5],
       [6, 7]])

- Dot product

In [45]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)

In [46]:
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [47]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [48]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32

### 6. Comparison

- all & any

In [49]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [51]:
np.any(a>5)     # 하나라도 True가 있으면 True

True

In [52]:
np.all(a>5)     # 모두가 True라야 True

False

- Logical operation

In [53]:
b = np.logical_and(a > 3, a < 7)
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [54]:
np.logical_or(a > 7, a < 3)

array([ True,  True,  True, False, False, False, False, False,  True,
        True])

- argmax, argmin

In [56]:
a.argmax(), np.argmax(a)

(9, 9)

In [57]:
a.argmin(), np.argmin(a)

(0, 0)

### 7. Boolean & Fancy indexing

- boolean indexing

In [58]:
# array a 에서 값이 6 이상인 것만 가져오기 - filtering
a[a >= 6]

array([6, 7, 8, 9])

In [59]:
a >= 6

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [60]:
b

array([False, False, False, False,  True,  True,  True, False, False,
       False])

In [61]:
a[b]

array([4, 5, 6])

- fancy indexing

In [62]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,3,2,1])     # a의 인덱스값
a[b]

array([2, 2, 4, 8, 6, 4])

### 8. 기술 통계

In [63]:
a = np.random.randn(10)
a

array([-1.71298203,  2.1160363 ,  0.59225789, -0.3296211 ,  1.61430781,
        0.99447171,  0.0694174 ,  0.16404078, -0.78152511,  0.92428242])

In [64]:
# 평균
np.mean(a), a.mean()

(0.3650686060380876, 0.3650686060380876)

In [65]:
# 표준편차(standard deviation)
np.std(a), a.std()

(1.0784413286262917, 1.0784413286262917)

In [66]:
# 최소, 최대
a.min(), a.max()

(-1.7129820343582638, 2.1160362968298516)

In [67]:
# 4분위수
np.percentile(a,25), np.percentile(a,50), np.percentile(a,75)

(-0.22986147775850824, 0.3781493381870402, 0.9769243841169115)

In [68]:
# 중앙값
np.median(a)

0.3781493381870402

In [69]:
a = np.random.randint(0,3,100)
a

array([2, 1, 1, 2, 0, 2, 1, 2, 0, 0, 2, 2, 1, 0, 2, 0, 2, 2, 1, 1, 0, 1,
       0, 1, 1, 2, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2, 0, 0, 1, 1, 2, 0, 2, 1,
       1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 2, 1, 2, 2, 1, 1, 0, 1,
       1, 1, 1, 2, 0, 0, 0, 1, 2, 2, 1, 2, 1, 0, 0, 1, 2, 1, 0, 1, 2, 2,
       0, 0, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1])

In [71]:
# 0, 1, 2 의 갯수
np.unique(a, return_counts=True)

(array([0, 1, 2]), array([24, 41, 35], dtype=int64))