# 연습문제

In [1]:
import numpy as np

### Q1. 행렬 만들기

In [2]:
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### Q2. Indexing, Slicing

In [4]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# 2-1, 2-2
m[1,2], m[-1,-1]

(7, 14)

In [6]:
# 2-3
m[1,1:3]

array([6, 7])

In [7]:
# slice가 행과 열에 적용되면 결과는 2차원
m[1:2, 1:3]

array([[6, 7]])

In [8]:
# 2-4
m[1:, 2]

array([ 7, 12])

In [9]:
m[1:, 2:3]

array([[ 7],
       [12]])

In [10]:
# 2-5
m[:-1, 3:]

array([[3, 4],
       [8, 9]])

### Q3. Boolean Indexing

In [11]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [13]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [14]:
f[np.logical_and(f%3==0, f%4==1)]

array([9])

### Q4. 대각선 행렬

In [18]:
np.eye(5,5,-1,int)*3 + np.eye(5,5,0,int)*2 + np.eye(5,5,1,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

### Q5. Matrix operation

In [21]:
np.random.seed(2021)
m = np.random.uniform(0, 10, 30).reshape(5, 6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [22]:
# 5-1
m.max()

9.9724

In [23]:
# 5-2
m.sum(axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [24]:
np.sum(m, axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [25]:
# 5-3
m.max(axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [27]:
# 5-4
m.mean(axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [28]:
# 5-5
m.min(axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

### Q6. Sorting

In [31]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [32]:
# 영어 성적을 argsort()
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [33]:
# 내림차순
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [34]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [35]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### Q7. 주사위 100번

In [36]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [37]:
np.mean(dice)

3.7

In [38]:
# dice array에서의 고유값
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [39]:
# dice array에서 고유값 및 그 갯수
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [41]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

### Q8. 정규분포, 주식

In [44]:
# 5개만 먼저 테스트
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')

10149 10218 10175 10093 10149 

In [45]:
# 250개
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_list = []
for i in range(250):
    price = price + np.round(price*rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])

In [46]:
np.random.seed(2021)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]

array([12072, 12210, 12255, 12359, 12292, 12262, 12136, 12010, 11984,
       12113])