# 연습문제

In [1]:
import numpy as np

### Q1. 행렬 만들기

In [2]:
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [3]:
np.arange(10,81,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### Q2. Indexing, Slicing

In [4]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
# 2-1, 2-2
m[1,2], m[-1,-1]

(7, 14)

In [6]:
# 2-3
m[1,1:3]

array([6, 7])

In [7]:
# 2차원으로 만들려면
m[1:2, 1:3]

array([[6, 7]])

In [ ]:
# slice가 행과 열에 적용되면 결과는 2차원
m[1:2, 1:3]

In [8]:
# 2-4
m[1:, 2]

array([ 7, 12])

In [9]:
m[1:, 2:3]

array([[ 7],
       [12]])

In [10]:
# 2-5
m[:-1, 3:]

array([[3, 4],
       [8, 9]])

### Q3. Boolean Indexing

In [11]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [13]:
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [16]:
f[np.logical_and(f%3==0, f%4==1)]

array([9])

### Q4. 대각선 행렬

In [17]:
np.eye(5,5,-1,int)*3 + np.eye(5,5,k=0,dtype=int)*2 + np.eye(5,5,1,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

### Q5. Matrix operation

In [18]:
np.random.seed(2022)
m = np.random.uniform(0, 10, 30).reshape(5, 6).round(4)
m

array([[0.0936, 4.9906, 1.1338, 0.4997, 6.8541, 4.8699],
       [8.9766, 6.4745, 8.9696, 7.2113, 8.3135, 8.2757],
       [8.3358, 9.5704, 3.6804, 4.9484, 3.3951, 6.1943],
       [9.7753, 0.9643, 7.4421, 2.925 , 2.9868, 7.5247],
       [0.1866, 5.2374, 8.6444, 3.8884, 2.1219, 4.7518]])

In [19]:
# 5-1
m.max()

9.7753

In [20]:
# 5-2
m.sum(axis=1)

array([18.4417, 48.2212, 36.1244, 31.6182, 24.8305])

In [21]:
np.sum(m, axis=1)

array([18.4417, 48.2212, 36.1244, 31.6182, 24.8305])

In [22]:
# 5-3
m.max(axis=1)

array([6.8541, 8.9766, 9.5704, 9.7753, 8.6444])

In [23]:
# 5-4
m.mean(axis=0)

array([5.47358, 5.44744, 5.97406, 3.89456, 4.73428, 6.32328])

In [24]:
# 5-5
m.min(axis=0)

array([0.0936, 0.9643, 1.1338, 0.4997, 2.1219, 4.7518])

### Q6. Sorting

In [25]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [26]:
# 영어 성적을 argsort()
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [27]:
# 내림차순
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [28]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [29]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### Q7. 주사위 100번

In [30]:
np.random.seed(2022)
dice = np.random.randint(1,7,100)
dice

array([6, 5, 6, 1, 2, 2, 1, 1, 3, 1, 1, 6, 2, 2, 4, 4, 4, 1, 4, 1, 4, 1,
       6, 1, 3, 3, 4, 2, 3, 1, 6, 6, 2, 6, 6, 5, 1, 3, 3, 3, 4, 5, 6, 2,
       3, 5, 1, 6, 6, 5, 3, 6, 1, 6, 6, 6, 6, 6, 1, 4, 4, 3, 5, 1, 2, 5,
       2, 1, 6, 6, 1, 1, 4, 2, 6, 4, 3, 2, 6, 3, 2, 5, 2, 3, 3, 2, 6, 2,
       3, 2, 5, 4, 1, 5, 5, 5, 5, 1, 2, 3])

In [31]:
np.mean(dice)

3.47

In [32]:
# dice array에서의 고유값
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [33]:
# dice array에서 고유값 및 그 갯수
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([20, 17, 16, 12, 13, 22], dtype=int64))

In [34]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 20, 2: 17, 3: 16, 4: 12, 5: 13, 6: 22}

### Q8. 정규분포, 주식

In [35]:
# 5개만 먼저 테스트
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')

10000 9973 9959 10157 10186 

In [37]:
# 위에서 구한 이자율(%)
rate * 100

array([-5.27899086e-04, -2.74901425e-01, -1.39285562e-01,  1.98468616e+00,
        2.82109326e-01])

In [38]:
# 250개 정규분포, 리스트 활용
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_list = []
for i in range(250):
    price = price + np.round(price*rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [39]:
# 정규분포, 어레이 활용
np.random.seed(2022)
rate = np.random.normal(0, 0.01, 250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i])
    price_array[i] = price

price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [44]:
# 표준정규분포를 이용한 경우
np.random.seed(2022)
rate = np.random.randn(250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price*rate[i]*0.01)
    price_array[i] = price

price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])